import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomepageBackground from "@/components/portfolio/background/HomepageBackground";
import CustomCursor from "@/components/cursor/CustomCursor";
import Copyright from "../components/portfolio/footer/Copyright";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <HomepageBackground />
        {/* Custom cursor above content */}
        <CustomCursor />
        <div className="relative z-10 min-h-dvh">{children}</div>
        {/* Copyright fetched client-side to avoid blocking SSR */}
        <Copyright />
      </body>
    </html>
  );
}
