import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomepageBackground from "@/components/portfolio/background/HomepageBackground";
import CustomCursor from "@/components/cursor/CustomCursor";
import { fetchUserPortfolio } from "@/services/portfolio.service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch copyright text from API; avoid static caching so it always reflects backend
  let copyright = "";
  try {
    const portfolio = await fetchUserPortfolio({ cache: "no-store" });
    copyright = portfolio.copyrights ?? "";
  } catch (e) {
    // ignore and use fallback
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <HomepageBackground />
        {/* Custom cursor above content */}
        <CustomCursor />
        <div className="relative z-10 min-h-dvh">
          {children}
        </div>
        {/* Static bottom-left copyright from API (fallback shown if empty) */}
        <div
          className="fixed left-4 bottom-4 z-20 text-[10px] md:text-xs text-white/60 tracking-wide select-none pointer-events-none"
          aria-label="Site copyright"
        >
          {`© ${new Date().getFullYear()} ${copyright}`}
        </div>
      </body>
    </html>
  );
}
